### ISSUE TITLE
Update SSDs

### ISSUE THREAD

**Issue by AndrewC0128** [baylorSailor/C.A.R.#23]
> This was a comment made by Matt in our Iteration 1 feedback.

The System sequence diagrams should be for specific use cases and there should be one for each use case. The ones that are present are not labeled and should be. There are two syntax issues in all of the ssds. First there are not colons in front of the roles of instances in the diagrams ( :System, :Employee). Second the arrow from the actor to the system is not the correct arrow. An actor should use a hollow arrow to send a message to the system.

**Comment by Wolfof365** [comment]
System Sequence Diagrams have all been finished for each use case.
