### ISSUE TITLE
Update Domain Model

### ISSUE THREAD

**Issue by AndrewC0128** [baylorSailor/C.A.R.#24]
> This was a comment made by Matt in our Iteration 1 feedback.

The domain model does not appear to show an association between a customer and a receipt so it seems that the system will not provide receipts to customers? Also a perhaps there should be a rental concept to track who has rented which vehicle when. I'm not certain of some of the associations in the model like customer to catalog. I'd recommend reviewing your model and ensuring that it tracks all that you will need it too.

**Comment by Wolfof365** [comment]
Domain Model is updated to match feedback, including adding a Rental class that has a car, a receipt, and a user.  Also, the Domain Model is done in such a way that it is, basically, our Design Class Diagram (happy accident).
