### ISSUE TITLE
Design Diagrams

### ISSUE THREAD

**Issue by AndrewC0128** [baylorSailor/C.A.R.#25]
e.g. Design Class diagram, Sequence/Communication diagrams
- 3 per each team member, package diagram if suitable

**Comment by Wolfof365** [comment]
Sequence/Communication Diagrams are finished, and the Design Class Diagram is the same as the Updated Domain Model in Iteration 1 Revised.

**Comment by Wolfof365** [comment]
Noticed that functions needed to be added

**Comment by Wolfof365** [comment]
Functions added and Design Class Diagram in now in Iteration 2 folder. Also reupdated Domain Model based on discussion with Mark Du to better represent User and Customer.

**Comment by Wolfof365** [comment]
Mistook Sequence Diagrams as a System Sequence Diagram, apologies.

**Comment by Wolfof365** [comment]
Design Class Diagram done!
