### ISSUE TITLE
SDs

### ISSUE THREAD

**Issue by AndrewC0128** [baylorSailor/C.A.R.#42]
- [x] Validate Username @maggie-burton 
- [x] Remove User @maggie-burton 
- [x] Add Car @AndrewC0128 
- [x] Remove Car @Drumshadow 
- [x] Create User  @Wolf1200 
- [x] Update User @baylorSailor 
- [x] Promote User @mdu2017 
- [x] Demote User @mdu2017 
- [x] Update Car @Drumshadow 
- [x] Pay Rental
- [x] Print Receipt
- [x] Create Rental
- [x] Edit Account
- [x] Search Car
- [x] Reset Password
- [x] Validate Card
- [x] Validate Username
- [x] Validate Email

**Comment by mdu2017** [comment]
All 18 sequence diagrams finished. In Iteration 2/Sequence Diagrams
