### ISSUE TITLE
Complete UI

### ISSUE THREAD

**Issue by AndrewC0128** [baylorSailor/C.A.R.#45]
Complete application with User Interface and user input validation

**Comment by baylorSailor** [comment]
I can help with UI stuff.

**Comment by AndrewC0128** [comment]
Things to be done:
- [x] Implement Logger @AndrewC0128 
- [x] Added JavaDoc @mdu2017 
- [ ] Add Different Users @Wolf1200 
- [x] Add Car Model @mdu2017 
- [x] Have Refresh Button Working
- [x] Implement History & Active Rentals CSV configuration
- [x] Added JUnit Tests @maggie-burton
