### ISSUE TITLE
Meeting Time

### ISSUE THREAD

**Issue by AndrewC0128** [baylorSailor/C.A.R.#47]
Figure meeting time during week?
Monday night?
Thursday night?

**Comment by Wolfof365** [comment]
Monday night, Wednesday and Friday any time after 12, and Tuesday and Thursday after class work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mdu2017** [comment]
Monday night
TR after class
Wed/Fri after 3pm

**Comment by baylorSailor** [comment]
Thursday after class and Friday after 5 works best for me.

**Comment by AndrewC0128** [comment]
Thursday night & Friday night/afternoon. 
@maggie-burton Do you want to play by ear for your schedule?

**Comment by AndrewC0128** [comment]
We will meet on Thursdays and as needed on weekends.
