### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by AndrewC0128** [baylorSailor/C.A.R.#48]
A document containing the general layout and usage/navigation of our UI.

**Comment by Drumshadow** [comment]
Finished the User Manual. I have the complete version locally and will push it soon

**Comment by AndrewC0128** [comment]
Reopened to remember to review syntax

**Comment by AndrewC0128** [comment]
Reopened to remember to review syntax

**Comment by mdu2017** [comment]
Finished
