### ISSUE TITLE
Finish Code

### ISSUE THREAD

**Issue by baylorSailor** [baylorSailor/C.A.R.#64]
Parse vehiclesSmall.csv and put results into the search results pane of the app.

**Comment by AndrewC0128** [comment]
Add pictures that correspond to the car

**Comment by AndrewC0128** [comment]
- [x] Fix adding vehicle issue (enum State)
- [x] Implement Buttons
- [x] Add Date Dropdown
- [ ] Representative edits history & active rentals
- [x] Fix Card Types
- [x] Add Representative Model
- [x] Implement Pictures in Search Pane
